import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AppSidebar } from "@/components/sidebar";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Finance Visualizer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SidebarProvider>
          <div className="flex min-h-screen w-screen">
            <AppSidebar />
            <main className="flex-1 w-full">
              <header className="bg-white shadow-md px-6 py-4 flex items-center justify-between">
                <h1 className="text-2xl uppercase md:text-3xl font-bold text-gray-900">
                  Finance Visualizer
                </h1>
                <SidebarTrigger />
              </header>
              {children}
            </main>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
